image: python:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  stage: test
  script:
    - pip install -r zad1/requirements.txt
    - pip install -r zad2/requirements.txt
    - pytest
