image: python:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  stage: test
  script:
    - pip install -r zad1/requirements.txt
    - pytest zad1
    - pip install -r zad2/requirements.txt
    - pytest zad2
    - pip install -r zad3/requirements.txt
    - pytest zad3
    - pip install -r zad4/requirements.txt
    - pytest zad4
